apiVersion: v1
data:
  admin-password: WW91clBhc3MxMjMj
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: prom
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2021-01-23T11:19:13Z"
  labels:
    app.kubernetes.io/instance: prom
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.3.5
    helm.sh/chart: grafana-6.1.17
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:admin-password: {}
        f:admin-user: {}
        f:ldap-toml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2021-01-23T11:19:13Z"
  name: prom-grafana
  namespace: monitoring
  resourceVersion: "652878"
  selfLink: /api/v1/namespaces/monitoring/secrets/prom-grafana
  uid: 00c52961-aad9-4e83-97b8-a7512166199a
type: Opaque
