apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"         # [OPTIONAL for Azure] if not provided, will default to "false"
    useVMManagedIdentity: "true"   # [OPTIONAL available for version > 0.0.4] if not provided, will default to "false"
    keyvaultName: "ohcontainer-kv"          # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: SQL-PASSWORD
          objectAlias: SQL_PASSWORD     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert. For Key Vault certificates, refer to https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md for the object type to use
        - |
          objectName: SQL-USER
          objectAlias: SQL_USER     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert. For Key Vault certificates, refer to https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md for the object type to use
        - |
          objectName: SQL-SERVER
          objectAlias: SQL_SERVER     # [OPTIONAL available for version > 0.0.4] object alias
          objectType: secret        # object types: secret, key or cert. For Key Vault certificates, refer to https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/docs/getting-certs-and-keys.md for the object type to use
    resourceGroup: "ohcontainer-rg"            # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: "4fe504a9-f5d1-4740-a5cf-532682d8fccf"         # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"                 # the tenant ID of the KeyVault