apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: api
  name: api-dev-rolebinding
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: c03eff94-250a-4d29-a40f-667ba8c2b9da # objectId of API-DEV group created in account tenant (here nssimon.com)
  apiGroup: rbac.authorization.k8s.io
  namespace: api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: web
  name: api-dev-rolebinding
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: c03eff94-250a-4d29-a40f-667ba8c2b9da
  apiGroup: rbac.authorization.k8s.io
  namespace: web
