apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: web
  name: web-dev-rolebinding
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: 844a01b1-5d6e-424c-9716-9a347d977565 # objectId of Web-Dev group in account tenant (here nssimon.com)
  apiGroup: rbac.authorization.k8s.io
  namespace: web
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: api
  name: web-dev-rolebinding
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: 844a01b1-5d6e-424c-9716-9a347d977565
  apiGroup: rbac.authorization.k8s.io
  namespace: api
