apiVersion: v1
kind: Secret
metadata:
  name: sql
  namespace: api
type: Opaque
data:
  SQL_USER: c3FsYWRtaW52TmIwOTk5Cg==
  SQL_PASSWORD: dlg2Z3c5RWM2Cg==
  SQL_SERVER: c3Fsc2VydmVydm5iMDk5OS5kYXRhYmFzZS53aW5kb3dzLm5ldAo=
  SQL_DBNAME: bXlkcml2aW5nREI=