apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: web
  labels:
    deploy: tripviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - image: "registryvnb0999.azurecr.io/tripviewer:1.0"
        imagePullPolicy: Always
        name: tripviewer
        resources:
          limits:
            memory: "400Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: "http://userprofile.api.svc.cluster.local"
          - name: TRIPS_API_ENDPOINT
            value: "http://trips.api.svc.cluster.local"
          - name: BING_MAPS_KEY
            value: "Ak8jy2wtOSzTX2ZIMowc6b0_SAFfTNXwCP9cl3hVNWy1xJN2CBR6i5k_9mftdQWA"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "aks-ingress"
  namespace: web
spec:
  type: LoadBalancer
  selector:
    app: tripviewer
  ports:
    - protocol: TCP
      name: tripviewer-http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: tripviewer-https
      port: 443
      targetPort: 443
