apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    prometheus.io/scrape: "true"
    prometheus.io/port: "9113"
  name: insurance-ingress
  namespace: insurance
spec:
  rules:
  - host: ohcontainer.westeurope.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: insurance
          servicePort: 80
        path: /insurance